- hosts: all

  gather_facts: no

  roles:
    - { role: setup, tags: ["all", "setup"] }
    - { role: website-files, tags: ["all", "files", "website-files"] }
    - { role: public-files, tags: ["all", "files", "public-files"] }
